"""Add created_at to Problem

Revision ID: 991e9e89a983
Revises: 89dbaec9865f
Create Date: 2024-07-19 11:59:55.072683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991e9e89a983'
down_revision = '89dbaec9865f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
